name: Docker Image CI

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      #realiza o download do artefato dist gerado por outro workflow
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #login no container registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3 #https://github.com/marketplace/actions/docker-login
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6 #https://github.com/marketplace/actions/build-and-push-docker-images
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/projeto-angular:latest
